# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  

steps:
- checkout: 'self'
  clean: true


- task:  DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
     command: 'restore'
     projects: '**/*.csproj'
  


  # ðŸ”¹ Build

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
   command: 'build'
   projects: '**/*.csproj'
   arguments: '--configuration  Debug '

# Publish

- task: DotNetCoreCLI@2
  displayName: 'Publish Web App'
  inputs:
     command: 'Publish'
     projects: '**/*.csproj'
     arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
     zipAfterPublish: true

# ðŸ”¹ Deploy karna hai  (ZIP create karega)
- task: AzureWebApp@1
  displayName: 'Deploy App'
  inputs:
    azureSubscription: 'azure-repo-app'
    appType: 'webApp'
    appName: 's1902'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'  # artifact path
    deploymentMethod: 'zipDeploy'                   # deployment type
    slotName: 'staging'   


  


